### ISSUE TITLE
Using watermark in Node.js causes ReferenceError

### ISSUE THREAD

**Issue by rubytomato** [pdfshift/pdfshift-node#1]
I am developing a demo program using Node.js and pdfshift package.
When using watermark in that demo program, a ReferenceError occurred.

My development environment is as follows.

* Windows 10
* Node.js 8.11.3
* pdfshift 1.0.3

For example, running the following code will cause a ReferenceError.

```javascript
  pdfshift.prepare(source)
  .watermark(
    {
    source: null,
    image: null,
    text: 'Top Secret',
    offset_x: 'center',
    offset_y: 'middle',
    rotate: 45,
    font_size: 46,
    font_color: '#f00',
    font_opacity: 50,
    font_bold: true,
    font_italic: true})
  .convert()
  .then(function (binary_file) {
    fs.writeFile('result.pdf', binary_file, "binary", function () {
      console.log('write callback');
    })
  })
  .catch(function({message, code, response, errors = null}) {
    console.error(message);
  });
```

This is the error message I got.

```text
ReferenceError: present is not defined
    at PDFShiftPrepared.watermark (D:\dev\vsc-workspace\demo-html-pdf\node_modules\pdfshift\index.js:119:17)
    at Object.<anonymous> (D:\dev\vsc-workspace\demo-html-pdf\simple.js:47:4)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:612:3
```

As I think, variable `present` does not seem to be defined.

```javascript
present = 0;
```

and then I think that `font_fold` is the typo of `font_bold`.

index.js:116

```js
watermark: function ({text = null, image = null, source = null, offset_x = null, offset_y = null, rotate = null, font_size = 16, font_family = null, font_color = null, font_opacity = 100, font_fold = false, font_italic = false}) {
```

Thanks.

**Comment by cnicodeme** [comment]
Hi!

Thank you for reporting this!

The updated package version 1.0.4 fixes the issue :)
